### ISSUE TITLE
How can i define a middlware?

### ISSUE THREAD

**Issue by zanhk** [florian-lefebvre/astro-integration-template#95]
I m not able to get middleware to work inside the integration, (https://docs.astro.build/en/guides/middleware/#basic-usage)

I created an empty middleware on the file `src/middleware.ts`

```ts
import { defineMiddleware } from "astro/middleware";

// `context` and `next` are automatically typed
export const onRequest = defineMiddleware(() => {});
```

And I m adding the middleware with

```ts
import { createResolver, defineIntegration } from "astro-integration-kit";

export const integration = defineIntegration({
	name: "package-name",
	setup() {
		return {
			hooks: {
				"astro:config:setup": (params) => {
					const { addMiddleware } = params;
					const { resolve } = createResolver(import.meta.url);
					addMiddleware({
						entrypoint: resolve("./middleware.ts"),
						order: "pre",
					});
				},
			},
		};
	},
});
```

(I tried with `src/middleware/index.ts` as well)

But when i run the playground I encouter the error

```
00:24:06 [ERROR] [MiddlewareCantBeLoaded] An unknown error was thrown while loading your middleware.
  Error reference:
    https://docs.astro.build/en/reference/errors/middleware-cant-be-loaded/
  Stack trace:
    at C:\Users\ZanK\Desktop\astro-integration-template-main\playground\C:\Users\ZanK\Desktop\astro-integration-template-main\node_modules\.pnpm\astro@4.10.2_@types+node@20.14.2_typescript@5.4.5\node_modules\astro\dist\core\middleware\loadMiddleware.js:8:24     
    [...] See full stack trace in the browser, or rerun with --verbose.
  Caused by:
  Cannot find module 'C:/Users/ZanK/Desktop/astro-integration-template-main/package/dist/middleware.ts' imported from 'astro-internal:middleware'
    at nodeImport (file:///C:/Users/ZanK/Desktop/astro-integration-template-main/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.2/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:53484:19)
    at eval (astro-internal:middleware:4:37)
00:24:06 [ERROR] [MiddlewareCantBeLoaded] An unknown error was thrown while loading your middleware.
  Error reference:
    https://docs.astro.build/en/reference/errors/middleware-cant-be-loaded/
  Stack trace:
    at C:\Users\ZanK\Desktop\astro-integration-template-main\playground\C:\Users\ZanK\Desktop\astro-integration-template-main\node_modules\.pnpm\astro@4.10.2_@types+node@20.14.2_typescript@5.4.5\node_modules\astro\dist\core\middleware\loadMiddleware.js:8:24     
    [...] See full stack trace in the browser, or rerun with --verbose.
  Caused by:
  Cannot find module 'C:/Users/ZanK/Desktop/astro-integration-template-main/package/dist/middleware.ts' imported from 'astro-internal:middleware'
    at nodeImport (file:///C:/Users/ZanK/Desktop/astro-integration-template-main/node_modules/.pnpm/vite@5.3.1_@types+node@20.14.2/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:53484:19)
    at eval (astro-internal:middleware:4:37)
```

Here a test repo which include only the changes described above: https://github.com/zanhk/astro-middleware-integration-tests, 

what am i missing?

Thanks

**Comment by florian-lefebvre** [comment]
Hi! For now, I recommend having an `assets` folder with untransformed files for this kind of stuff. Example here:
- https://github.com/astrolicious/i18n/blob/main/package/package.json#L41-L44
- https://github.com/astrolicious/i18n/blob/main/package/assets/middleware.ts
- https://github.com/astrolicious/i18n/blob/main/package/src/integration.ts#L31-L34

**Comment by zanhk** [comment]
Thanks!
